### ISSUE TITLE
The `Done` button not showing in small screen

### ISSUE THREAD

**Issue by williambao** [SchibstedSpain/Leku#103]
Hi, 
My app is need to install on the small screen size device.
But when I open picker activity, the `Done` button not showing.
It there any parameter to set `Done` button position ?
<img width="351" alt="leku" src="https://user-images.githubusercontent.com/779521/28121155-cff28912-674c-11e7-9b6f-ab906353823c.png">

And another problem is the buttons  color are always gray.

Thanks,

## Info Required

- Which version of the library do you actually use?
3.4.0
- Do you have the localization permission granted?
no
- Are you sending parameters to the activity through the bundle?
N
- Could you describe what are the actions do you make to raise that error?
N
- Android monitor shows any log related to the library when the error is shown?
N
- Any other thing that could help me to reproduce the error?
N

**Comment by Kharestani** [comment]
I have the same problem! If you solve this we will really appreciate it.

thanks

**Comment by ferranpons** [comment]
@williambao as I see in your screenshot and what you say... It does not appear because you don't have any location selected. Remember that is a "location picker" so if you haven't picked any location it's not possible to display the "Done" action.

First, you don't have location permission so it doesn't select it by default. 
Second, if you did not search any location it's impossible to display the `done` button.
Third, if you have the maps key added you would see the map and you are going to be able to select a location using the map.

Hope it helps. 😉

**Comment by ferranpons** [comment]
@williambao are you still experiencing this issue? 

I'm closing this issue, if you are still experiencing this problem please reopen the issue.

Many thanks for reporting! 😉
