### ISSUE TITLE
Search View not working properly.

### ISSUE THREAD

**Issue by honey-hoper** [SchibstedSpain/Leku#114]
Hi, I'm from India. I used your library and it is working pretty awesome. But the problem is that the search view isn't working properly. It only shows some results. I have also set the search zone to India but still no luck. Well it is not that important to my application so I was thinking of removing it. Is there any way to remove it?

**Comment by ferranpons** [comment]
@honey-hoper first of all thanks for reporting these issues. Search Zone feature must be reworked due to it's not working properly because it's tied to Geocoder that does not always work as expected.

About enabling/disabling search view, I would need to add the option to the library. I'll try to add it as soon as possible.

Thanks for using this library and for your patience!

**Comment by honey-hoper** [comment]
Thanks alot!
Great work, keep it up!

**Comment by ch4rl3s** [comment]
Hi, someone have new about this? thanks.

**Comment by honey-hoper** [comment]
@ch4rl3s not working

**Comment by ferranpons** [comment]
Sorry, I still had no time to work on it. 😞

**Comment by honey-hoper** [comment]
np, take your time

**Comment by ferranpons** [comment]
@honey-hoper @ch4rl3s I've just published a new version of the library that should solve the issues that are you experiencing with the search view. (v3.6.0)
I'm closing the issue, if you are still experiencing this issue please re-open it again.

Many thanks for reporting the issue and for your patience!
