### ISSUE TITLE
Did Leku support Runtime permission?

### ISSUE THREAD

**Issue by anticafe** [SchibstedSpain/Leku#14]
This is just my question. I'm not sure if your library supports Runtime Permission of Android 6?

**Comment by ferranpons** [comment]
Hi @anticafe! Sure, it supports runtime permissions for Android 6! You don't need to do anything, it will ask for permissions if needed. We also removed all the hassle of controlling errors and the lifecycle of the component. The problem is that it was not explained in the Readme.

I've updated the documentation to reflect this. Thanks for pointing it out!

**Comment by ferranpons** [comment]
Solved with PR #15

**Comment by anticafe** [comment]
Thanks for your reply. Yeah, with Runtime Permission support, it's really cool. I'm going to integrate this library into my app. It would save me a lot of time.

**Comment by ferranpons** [comment]
You're welcome! Thanks to you for using it!

![happy dance](http://i.giphy.com/TPh2mykH0wEMw.gif)
