### ISSUE TITLE
Google play services 9.6.1

### ISSUE THREAD

**Issue by borjaruiz** [SchibstedSpain/Leku#39]
I have a problem when compiling my project. After updating all my google dependencies to 9.6.1, an error is shown:

All com.google.android.gms libraries must use the exact same version. (9.6.1)

I think this is caused because Leku uses maps:9.4.0 

Is there any solution without needing to update Leku library?

Thanks in advance

**Comment by ferranpons** [comment]
@borjaruiz updating your dependencies to 9.6.1 should not be an issue because gradle will use the upper version for all the dependencies that include that library.

The problem is that the build tools is raising that error to the IDE. So if you're using a build tools version below 24.0.3 please update it to that version and the error will disappear. 😉

**Comment by ferranpons** [comment]
Looks like AS has some issue with that version of com.google.android.gms:play-services-maps. Maybe is an issue introduced with that version because if I create a new library with only that dependency with version 9.6.1 still raises the error. I'll try to find more about this but, for now, you could do to things:

- Go back to the version 9.4.0 if you don't need anything specific of the 9.6.1 version.
- Use 9.6.1 and ignore the error. It will build your application without problems, just show the lint error on the IDE.

¯\\\_(ツ)_/¯

**Comment by borjaruiz** [comment]
Hi @ferranpons ,
Going back to previous version is not a possible solution because firebase has solved some critical bugs.
If I use 9.6.1 and try to generate a production APK, log shows a lot of errors related to maps and location, and I can't create the apk. :(

compileSdkVersion 23
targetSdkVersion 23
buildToolsVersion "24.0.3"

Thanks

**Comment by ferranpons** [comment]
@borjaruiz after digging a bit more I've found that google maps now requires google places! Grrrr!

You will solve the issue by adding to your project:

compile "com.google.android.gms:play-services-places:9.6.1"

![giphy 35](https://cloud.githubusercontent.com/assets/1225463/19230585/a5143cfe-8ed5-11e6-94d7-5fc24c9c88e7.gif)

**Comment by borjaruiz** [comment]
Yes, it was my fault, it works now! Thanks!
