### ISSUE TITLE
Same problem as #61, but with cloned repo

### ISSUE THREAD

**Issue by enzonotario** [SchibstedSpain/Leku#64]
Hi! I'm trying to use this library and have the same problem that the issue #61 (can't select a position, can't search)

I cloned this repo, thinking that maybe I'm doing something wrong in my app, but I have the same problem in the repo app, where I just modify the GoogleMap API_KEY.

I have a Samsung Grand Prime... What can be the problem?

Thanks!

**Comment by MaxMello** [comment]
Hey, I don't know if you are already familiar with Android development. I surely am not, but I found that API key related functionality may need a few days to work correctly. My Twitter Login wasn't working after I changed the API key as well for a few days. After that, it just worked. If your keys are freshly generated, it may take a few days to work. Did you check your Google Developer Console for incoming requests for your API key? I wonder though if this problem was always common or if these few incidents in the last days were abnormal. Hope you will get your problem fixed :)

**Comment by enzonotario** [comment]
I check my Google Developer Console and yes, it has 5 requests...

But how can I accept these requests?

Sorry, but I'm new in the Android development and moreover I don't speak english, so it's so hard to me find in google or in documentation..

Thanks for the reply and hope that you can help me

**Comment by ferranpons** [comment]
@enzonotario have you tried this in another device?

**Comment by enzonotario** [comment]
Hi! Sorry, my mistake, it nows works.
I have to add ```compile 'com.google.android.gms:play-services:10.0.1'```
I only had these "compiles":
```
    compile "com.google.android.gms:play-services-location:10.0.1"
    compile 'com.google.android.gms:play-services-maps:10.0.1'
    compile 'com.google.android.gms:play-services-auth:10.0.1'
```

I add "all" play-services and now it works. Sorry, but i had read in any place that I have to add only the play-services-* that I will use, I think that with play-services-maps will be enough, it seems that not.

Sorry, but newbie here!...

Thanks!

**Comment by ferranpons** [comment]
Hi @enzonotario!

No problem at all! I'm here to help. 😉 

Instead of using the whole play-services library you must use only what you need because you will add a lot of weight to you application.

For what you say, it's possible that you will need you to include the "places" compile. Version 9.6.0 of play services required it in order to work correctly. You can check out issue #39 

If you need more help don't hesitate to ask here.



Thanks!
